// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using makalesistemi.Models;

#nullable disable

namespace makalesistemi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250323090701_yeniveritabani")]
    partial class yeniveritabani
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("makalesistemi.Models.Anonimlestirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakaleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MakaleId");

                    b.ToTable("Anonimlestirmeler");
                });

            modelBuilder.Entity("makalesistemi.Models.Editor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Editorler");
                });

            modelBuilder.Entity("makalesistemi.Models.Hakem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hakemler");
                });

            modelBuilder.Entity("makalesistemi.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakaleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MakaleId");

                    b.ToTable("Loglar");
                });

            modelBuilder.Entity("makalesistemi.Models.Makale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnonimDosyaYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegerlendirmeDosyaYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("HakemDegerlendirmesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HakemId")
                        .HasColumnType("int");

                    b.Property<string>("TakipNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YazarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HakemId");

                    b.HasIndex("YazarId");

                    b.ToTable("Makaleler");
                });

            modelBuilder.Entity("makalesistemi.Models.Sohbet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GondericiId")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakaleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GondericiId");

                    b.HasIndex("MakaleId");

                    b.ToTable("Sohbetler");
                });

            modelBuilder.Entity("makalesistemi.Models.Yazar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yazarlar");
                });

            modelBuilder.Entity("makalesistemi.Models.Anonimlestirme", b =>
                {
                    b.HasOne("makalesistemi.Models.Makale", "Makale")
                        .WithMany("Anonimlestirmeler")
                        .HasForeignKey("MakaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makale");
                });

            modelBuilder.Entity("makalesistemi.Models.Log", b =>
                {
                    b.HasOne("makalesistemi.Models.Makale", "Makale")
                        .WithMany("Loglar")
                        .HasForeignKey("MakaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makale");
                });

            modelBuilder.Entity("makalesistemi.Models.Makale", b =>
                {
                    b.HasOne("makalesistemi.Models.Hakem", "Hakem")
                        .WithMany("Makaleler")
                        .HasForeignKey("HakemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("makalesistemi.Models.Yazar", "Yazar")
                        .WithMany("Makaleler")
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hakem");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("makalesistemi.Models.Sohbet", b =>
                {
                    b.HasOne("makalesistemi.Models.Yazar", "Gonderici")
                        .WithMany("Sohbetler")
                        .HasForeignKey("GondericiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("makalesistemi.Models.Makale", "Makale")
                        .WithMany("Sohbetler")
                        .HasForeignKey("MakaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gonderici");

                    b.Navigation("Makale");
                });

            modelBuilder.Entity("makalesistemi.Models.Hakem", b =>
                {
                    b.Navigation("Makaleler");
                });

            modelBuilder.Entity("makalesistemi.Models.Makale", b =>
                {
                    b.Navigation("Anonimlestirmeler");

                    b.Navigation("Loglar");

                    b.Navigation("Sohbetler");
                });

            modelBuilder.Entity("makalesistemi.Models.Yazar", b =>
                {
                    b.Navigation("Makaleler");

                    b.Navigation("Sohbetler");
                });
#pragma warning restore 612, 618
        }
    }
}
